# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 150059ca867837a064d6a8d452dc6142d409fd46a7448c7ea33d92cd5ef71f784960213c838eed8b77dcb4e680d5cc77311e40810da121d2e9a09f774eb018f0

test:
  secret_key_base: a6059f2245b839d8a9359f22cd3816b34935bea4ad7dbd9b8494f61a7a615f66b34290c20bf06c4d86b8b3fecb01e869e83d82a6a039ef9a95c8e61d38b7ed9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
